// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: v1/hooks.proto

package subflowv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SubscriptionHooks_Dispatch_FullMethodName = "/subflow.hooks.v1.SubscriptionHooks/Dispatch"
)

// SubscriptionHooksClient is the client API for SubscriptionHooks service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SubscriptionHooksClient interface {
	Dispatch(ctx context.Context, in *Event, opts ...grpc.CallOption) (*HookAck, error)
}

type subscriptionHooksClient struct {
	cc grpc.ClientConnInterface
}

func NewSubscriptionHooksClient(cc grpc.ClientConnInterface) SubscriptionHooksClient {
	return &subscriptionHooksClient{cc}
}

func (c *subscriptionHooksClient) Dispatch(ctx context.Context, in *Event, opts ...grpc.CallOption) (*HookAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HookAck)
	err := c.cc.Invoke(ctx, SubscriptionHooks_Dispatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SubscriptionHooksServer is the server API for SubscriptionHooks service.
// All implementations should embed UnimplementedSubscriptionHooksServer
// for forward compatibility.
type SubscriptionHooksServer interface {
	Dispatch(context.Context, *Event) (*HookAck, error)
}

// UnimplementedSubscriptionHooksServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSubscriptionHooksServer struct{}

func (UnimplementedSubscriptionHooksServer) Dispatch(context.Context, *Event) (*HookAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Dispatch not implemented")
}
func (UnimplementedSubscriptionHooksServer) testEmbeddedByValue() {}

// UnsafeSubscriptionHooksServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SubscriptionHooksServer will
// result in compilation errors.
type UnsafeSubscriptionHooksServer interface {
	mustEmbedUnimplementedSubscriptionHooksServer()
}

func RegisterSubscriptionHooksServer(s grpc.ServiceRegistrar, srv SubscriptionHooksServer) {
	// If the following call pancis, it indicates UnimplementedSubscriptionHooksServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SubscriptionHooks_ServiceDesc, srv)
}

func _SubscriptionHooks_Dispatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Event)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionHooksServer).Dispatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionHooks_Dispatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionHooksServer).Dispatch(ctx, req.(*Event))
	}
	return interceptor(ctx, in, info, handler)
}

// SubscriptionHooks_ServiceDesc is the grpc.ServiceDesc for SubscriptionHooks service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SubscriptionHooks_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "subflow.hooks.v1.SubscriptionHooks",
	HandlerType: (*SubscriptionHooksServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Dispatch",
			Handler:    _SubscriptionHooks_Dispatch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/hooks.proto",
}
